name: slice

on:
  push:
  schedule:
    - cron:  '0 * * * *'

jobs:
  build:

    runs-on: ubuntu-20.04
    env:
      access_token: ${{ secrets.ACCESS_TOKEN }}

    steps:
    - uses: actions/checkout@v2.3.4

    - name: checkout
      run: git clone https://github.com/minetest/minetest_game

    - name: default
      run: ./slice.sh default

    - name: beds
      run: ./slice.sh beds

    - name: dye
      run: ./slice.sh dye

    - name: xpanes
      run: ./slice.sh xpanes

    - name: player_api
      run: ./slice.sh player_api
